spring:
  datasource:
    url:
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      transport.protocol: smtp
      mail.smtp:
        auth: true
        starttls.enable: true
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
oauth:
  jwt.key: test
  client:
    id: ama
    secret: ama
  token.validity: 86400
captcha:
  enable: false
  url: https://www.google.com/recaptcha/api/siteverify?secret={secret}&response={response}
  secret:
  site:
registration:
  url: http://localhost:8081/register/activate?token=
crypto:
  aes:
    key:
    salt: