-- admin@admin / admin
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_NAME, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'admin@admin', '$2a$10$Tbt2mTwOerxIn396uy0x4eOKz3vXYqYQ.5Ntd7E5bkrklT7NIAiqi', 'Admin Admin', TRUE);
-- business@business / business
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_NAME, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'business@business', '$2a$10$0yycAdw4CZ/gQwqQZrvhl.pwfMq/51m1gNm9uHI.Ld/D7IqEm.iMa', 'Business Business', TRUE);
-- user@user / user
INSERT INTO USERS (USR_ID, USR_EMAIL, USR_PASSWORD, USR_NAME, USR_ACTIVE) VALUES (NEXTVAL('SEQ_USR'), 'user@user', '$2a$10$il1TVNe5l6dlHQ5LGAdQOOQfv81fUS4fw.l8DqISUXhEN1A0n6q6W', 'User User', TRUE);

INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (NEXTVAL('SEQ_ROL'), 'ADMIN');
INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (NEXTVAL('SEQ_ROL'), 'BUSINESS');
INSERT INTO ROLES (ROL_ID, ROL_ROLE)	VALUES (NEXTVAL('SEQ_ROL'), 'USER');

INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'ADMIN'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'BUSINESS'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'admin@admin'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'business@business'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'BUSINESS'));
INSERT INTO USER_ROLES (URL_USR_ID, URL_ROL_ID) VALUES ((SELECT USR_ID FROM USERS WHERE USR_EMAIL = 'user@user'), (SELECT ROL_ID FROM ROLES WHERE ROL_ROLE = 'USER'));
